broker_kafka: rbmqsp2ndx5r.redborder.cluster:9092
s3_bucket: malware/mdata/input/
access_key: JFH-SQJ9V4MRSWQ941C4
secret_key: 0u1NVkoHI5j1hOE1vwrIQN0xwrIybi3EMkBeLg==
cache_direction: 10.0.161.211:7777
version_cache: v1
domain_id: 2000
score: 50
bitacora_size: 262144
logs_size: 262144
file_size: 134217728
client_id: C.111111111111111
